pipeline {
    // Agent we will use any Agent Node in the Jenkins to run this pipeline
    agent any

    tools {
        // Mention the Tool configured in the Jenkins Server like Java, Maven, Git 
        maven 'Maven_Tool'
        jdk 'Java_Tool'
    }

    // Set Environment Variable for the Nexus to interact to download the dependencies and upload artifacts in the Nexus
    environment {

        NEXUS_USER = 'admin'
        NEXUS_PASS = 'admin'
        RELEASE_REPO = 'vprofile-release'
        CENTRAL_REPO = 'vprofile-maven-central'
        SNAP_REPO = 'vprofile-snapshot'
        NEXUS_GRP_REPO = 'vprofile-maven-group'
        NEXUSIP = '172.31.32.231'
        NEXUSPORT = '8081'
        NEXUS_LOGIN = 'NEXUS_CREDENTIALS'
        SONAR_SCANNER = 'sonarqubescanner'
        SONAR_SERVER_LOGIN = 'sonarserver'
        AWS_ACCOUNT_ID = '115246381799'
        registryCredentials = 'ecr:ap-south-1:AWS_CRED' // JEnkins will use this credential to login to the AWS ECR and push the docker image
        appRegistry = '115246381799.dkr.ecr.ap-south-1.amazonaws.com/vprofileappimg' // ECR Registry where we will push the docker image
        vprofileAppImg = 'https://115246381799.dkr.ecr.ap-south-1.amazonaws.com'  

    }

    stages {
        stage('Build Applications') {
            steps {
                sh 'mvn -s settings.xml -DskipTests install' // Run Install and use setting.xml file and skip unit test
            }
            post {
                success {
                    echo 'Now Archiving'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        // Test Application
        stage('Test Application') {
            steps {
                sh 'mvn test'
            }
        }

        // Check Style Application for Vulnerability scan
        stage('CheckStyle for the Application') {
            steps {
                sh 'mvn checkstyle:checkstyle'
            }
        }

        // Upload Report to the Sonar Server to check the Vulnerability. Refer Documentation for code
        stage('Sonar Qube Analysis') {
            environment {
                    scannerhome = tool "${SONAR_SCANNER}" // Mention the name used while configuring sonarscanner in the jenkins tools 
                    // ADD THIS LINE BELOW to fix the Java 17 error
                    
                    SONAR_SCANNER_OPTS = "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED"
                }


            steps {
                withSonarQubeEnv("${SONAR_SERVER_LOGIN}") {
                    sh '''${scannerhome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile-repo \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                } 
            }
        }
        stage('Validate Quality Gates') {
            steps {
                //timeout is 1 hrs
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        // Upload Artifacts to the Nexus Repos
        stage('Upload Artifacts') {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                    groupId: 'QA',
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                    repository: "${RELEASE_REPO}",
                    credentialsId: "${NEXUS_LOGIN}",
                    artifacts: [
                        [artifactId: 'vproapp',
                        classifier: '',
                        file: 'target/vprofile-v2.war',
                        type: 'war']
                    ]
                )
            }
        }

        // Build Docker File
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${appRegistry}-${BUILD_NUMBER}", "./Docker-files/app/multistage/") // Build the Docker Image. Using Plugin we have used docker with build method and this method has two argument 1st Name of the Image and Second path of the DockerFile
                }
            }
        }

        // Upload Docker Image to the AWS ECR
        stage('Upload Docker Image') {
            steps {
                script {
                    docker.withRegistry(vprofileAppImg, registryCredentials) // Login to the AWS ECR using the credentials configured in the jenkins and using the URL of the ECR registry
                    {
                        dockerImage.push("BUILD_NUMBER") // Push the docker image to the ECR with Tag
                        dockerImage.push("Latest")
                    }
                }
            }
        }
    }

    // Email Notification Of the Status of Pipeline 
    post {
        always {
            echo 'Pipeline has been completed Sending Pipeline Status through Email...'
            emailext (
                body: """<p>Jenkins Build Status: <b>${currentBuild.currentResult}</b></p>
                         <p>Job Name: ${env.JOB_NAME}</p>
                         <p>Build Number: ${env.BUILD_NUMBER}</p>
                         <p>Check console output at: <a href='${env.BUILD_URL}'>${env.BUILD_URL}</a></p>""",
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME} | ${env.BUILD_NUMBER}", 
                to: 'puneethkumar482000@gmail.com'
            )
        }
    }
}